/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import java.awt.Button;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.border.Border;


/**
 *
 * @author DELL
 */
public class GameView extends javax.swing.JFrame {
    private SButton boardButtonP1[];
    private SButton boardButtonP2[];
    private ScoreBoard infoP1TA;
    
    private ScoreBoard infoP2TA;

    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    public JTextField getTestTF() {
        return notifyTF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        notifyTF = new javax.swing.JTextField();
        backB = new javax.swing.JButton();
        boardP1 = new javax.swing.JPanel();
        boardP2 = new javax.swing.JPanel();
        readyP2B = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatTA = new javax.swing.JTextArea();
        sendB = new javax.swing.JButton();
        readyP1B = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        messageTF = new javax.swing.JTextField();
        roomNameL = new javax.swing.JLabel();
        boardJP1 = new javax.swing.JPanel();
        boardJP2 = new javax.swing.JPanel();

        jScrollPane4.setViewportView(jEditorPane1);

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Battle Ship");

        notifyTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notifyTF.setText("Bạn có 20s để đặt 5 tàu vào bản đồ<Thiếu 2 tàu>! 15s...");
        notifyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyTFActionPerformed(evt);
            }
        });

        backB.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        backB.setText("Thoát");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardP1Layout = new javax.swing.GroupLayout(boardP1);
        boardP1.setLayout(boardP1Layout);
        boardP1Layout.setHorizontalGroup(
            boardP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        boardP1Layout.setVerticalGroup(
            boardP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout boardP2Layout = new javax.swing.GroupLayout(boardP2);
        boardP2.setLayout(boardP2Layout);
        boardP2Layout.setHorizontalGroup(
            boardP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        boardP2Layout.setVerticalGroup(
            boardP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        readyP2B.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        readyP2B.setText("Sẵn sàng");
        readyP2B.setEnabled(false);
        readyP2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyP2BActionPerformed(evt);
            }
        });

        chatTA.setColumns(20);
        chatTA.setRows(5);
        jScrollPane3.setViewportView(chatTA);

        sendB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sendB.setText("Gửi");
        sendB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBActionPerformed(evt);
            }
        });

        readyP1B.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        readyP1B.setText("Sẵn sàng");
        readyP1B.setEnabled(false);
        readyP1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyP1BActionPerformed(evt);
            }
        });

        jLabel2.setText("Chat");

        messageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTFActionPerformed(evt);
            }
        });

        roomNameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout boardJP1Layout = new javax.swing.GroupLayout(boardJP1);
        boardJP1.setLayout(boardJP1Layout);
        boardJP1Layout.setHorizontalGroup(
            boardJP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        boardJP1Layout.setVerticalGroup(
            boardJP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout boardJP2Layout = new javax.swing.GroupLayout(boardJP2);
        boardJP2.setLayout(boardJP2Layout);
        boardJP2Layout.setHorizontalGroup(
            boardJP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardJP2Layout.setVerticalGroup(
            boardJP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boardP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                        .addComponent(boardP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boardJP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(messageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sendB))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(75, 75, 75)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boardJP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(readyP1B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(notifyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(readyP2B))
                                    .addComponent(roomNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomNameL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(notifyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readyP2B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readyP1B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boardP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(messageTF)
                            .addComponent(sendB, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boardJP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(boardJP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notifyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifyTFActionPerformed

    private void readyP2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyP2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readyP2BActionPerformed

    private void readyP1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyP1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readyP1BActionPerformed

    private void sendBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendBActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBActionPerformed

    private void messageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
                
            }
        });
    }
    public void init(){
        boardP1.setLayout(new GridLayout(4,5));
        boardP2.setLayout(new GridLayout(4,5));
        boardButtonP1 = new SButton[20];
        boardButtonP2 = new SButton[20];
        infoP1TA = new ScoreBoard();
        infoP2TA = new ScoreBoard();
        infoP1TA.setSize(300, 400);
        infoP2TA.setSize(300, 400);
        infoP1TA.setLayout(new GridLayout(1,1));
        infoP2TA.setLayout(new GridLayout(1,1));
        boardJP1.add(infoP1TA);
        boardJP2.add(infoP2TA);
        
        for(int i=0;i<20;i++){
            boardButtonP1[i]=new SButton(i);
            boardButtonP2[i]=new SButton(i);
            boardP1.add( boardButtonP1[i]);
            boardP2.add(boardButtonP2[i]);
            boardButtonP1[i].setBackground(Color.CYAN);
            boardButtonP2[i].setBackground(Color.red);
            boardButtonP1[i].setImage(3);
            boardButtonP2[i].setImage(4);
            
        }
        boardP1.setBackground(Color.WHITE);
        boardP2.setBackground(Color.WHITE);
        notifyTF.setEditable(false);
        
        infoP1TA.setEditable(false);
        infoP2TA.setEditable(false);
       // boardButtonP1[3].setMargin(new Insets(0, 0, 0, 0));
        
    }

    public SButton[] getBoardButtonP1() {
        return boardButtonP1;
    }

    public SButton[] getBoardButtonP2() {
        return boardButtonP2;
    }

    public JPanel getBoardP1() {
        return boardP1;
    }

    public JPanel getBoardP2() {
        return boardP2;
    }

    public JTextArea getChatTA() {
        return chatTA;
    }

    public ScoreBoard getInfoP1TA() {
        return infoP1TA;
    }

    public ScoreBoard getInfoP2TA() {
        return infoP2TA;
    }

   
    
    public JTextField getMessageTF() {
        return messageTF;
    }

    public JTextField getNotifyTF() {
        return notifyTF;
    }

    public JButton getReadyB1B() {
        return readyP2B;
    }

    public JButton getReadyP1B() {
        return readyP1B;
    }

    public JButton getSendB() {
        return sendB;
    }
    
    
    public JButton getBackB() {
        return backB;
    }

    public JLabel getRoomNameL() {
        return roomNameL;
    }

    public JButton getReadyP2B() {
        return readyP2B;
    }
    public void updateInfo(JTextArea form,int player,String name,int x,int y, int score){
        form.setText("");
        
        
    }
    public void disableBoard(SButton boardButton[]){
        for(int i=0;i<boardButton.length;i++)
            boardButton[i].setEnabled(false);
    }
    public void enableBoard(SButton boardButton[]){
        for(int i=0;i<boardButton.length;i++)
        if(boardButton[i].getType()!=6){
            boardButton[i].setEnabled(true);
        }
    }
    public void resetBoard(SButton boardButton[],int type,Color color){
        for(int i=0;i<boardButton.length;i++){
            boardButton[i].setEnabled(true);
            boardButton[i].setVisible(true);
            boardButton[i].setBackground(color);
            boardButton[i].setImage(type);
        }
    }
    public void removeActionListener(){
        for(ActionListener al:readyP1B.getActionListeners()){
            readyP1B.removeActionListener(al);
        }
        for(ActionListener al:readyP2B.getActionListeners()){
            readyP2B.removeActionListener(al);
        }
        for(SButton b:boardButtonP2){
            for(ActionListener al:b.getActionListeners()){
                b.removeActionListener(al);
            }
        }
        for(SButton b: boardButtonP1){
            for(ActionListener al:b.getActionListeners()){
                b.removeActionListener(al);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JPanel boardJP1;
    private javax.swing.JPanel boardJP2;
    private javax.swing.JPanel boardP1;
    private javax.swing.JPanel boardP2;
    private javax.swing.JTextArea chatTA;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField messageTF;
    private javax.swing.JTextField notifyTF;
    private javax.swing.JButton readyP1B;
    private javax.swing.JButton readyP2B;
    private javax.swing.JLabel roomNameL;
    private javax.swing.JButton sendB;
    // End of variables declaration//GEN-END:variables
}
